# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Default size of the steps in the RK
#' 
#' Computes the default step lenght for a matrix \code{T} to be employed in the RK method
#' @param T sub-intensity matrix
#' @return The step lenght for \code{T}
#' 
default_step_length <- function(T) {
    .Call(`_matrixdist_default_step_length`, T)
}

#' Runge Kutta for the calculation of the a,b and c vectors in a EM step
#' 
#' Performce the RK of forth order
#' @param avector the a vector
#' @param bvector the b vector 
#' @param cmatrix the c matrix
#' @param dt the increment
#' @param h step-lenght
#' @param T sub-intensity
#' @param t exit rates 
#' 
runge_kutta <- function(avector, bvector, cmatrix, dt, h, T, t) {
    invisible(.Call(`_matrixdist_runge_kutta`, avector, bvector, cmatrix, dt, h, T, t))
}

#' EM step using Runge Kutta
#' 
#' Computes one step of the EM algorithm by using a Runge-Kutta method of 4th order
#' @param h step-lenght
#' @param pi initial probalities
#' @param T sub-intensity
#' @param obs the observations
#' @param weight the weights for the observations
#' @param rcens censored observations
#' @param rcweight the weights for the censored observations
#' 
EMstep_RK <- function(h, pi, T, obs, weight, rcens, rcweight) {
    invisible(.Call(`_matrixdist_EMstep_RK`, h, pi, T, obs, weight, rcens, rcweight))
}

#' Runge Kutta for the calculation of the a vectors in a EM step 
#' 
#' Can be used for the loglikelihood
#' @param avector the a vector
#' @param dt increment
#' @param h step-lenght
#' @param T sub-intensity
#' 
a_rungekutta <- function(avector, dt, h, T) {
    invisible(.Call(`_matrixdist_a_rungekutta`, avector, dt, h, T))
}

#' Loglikelihood using RK
#' 
#' Loglikelihood for a sample 
#' @param h step-lenght
#' @param pi initial probabilities
#' @param T sub-intensity
#' @param obs the observations
#' @param weight weight of the observations
#' @param rcens censored observations
#' @param rcweight weight of the censored observations
#' 
logLikelihoodPH_RK <- function(h, pi, T, obs, weight, rcens, rcweight) {
    .Call(`_matrixdist_logLikelihoodPH_RK`, h, pi, T, obs, weight, rcens, rcweight)
}

#' Loglikelihood of matrix Weibull using RK
#' 
#' Loglikelihood for a sample 
#' @param h step-lenght
#' @param pi initial probabilities
#' @param T sub-intensity
#' @param beta parametor of transformation
#' @param obs the observations
#' @param weight weight of the observations
#' @param rcens censored observations
#' @param rcweight weight of the censored observations
#' 
logLikelihoodMWeibull_RK <- function(h, pi, T, beta, obs, weight, rcens, rcweight) {
    .Call(`_matrixdist_logLikelihoodMWeibull_RK`, h, pi, T, beta, obs, weight, rcens, rcweight)
}

#' Loglikelihood of matrix Pareto using RK
#' 
#' Loglikelihood for a sample 
#' @param h step-lenght
#' @param pi initial probabilities
#' @param T sub-intensity
#' @param beta parametor of transformation
#' @param obs the observations
#' @param weight weight of the observations
#' @param rcens censored observations
#' @param rcweight weight of the censored observations
#' 
logLikelihoodMPareto_RK <- function(h, pi, T, beta, obs, weight, rcens, rcweight) {
    .Call(`_matrixdist_logLikelihoodMPareto_RK`, h, pi, T, beta, obs, weight, rcens, rcweight)
}

#' Loglikelihood of matrix LogNormal using RK
#' 
#' Loglikelihood for a sample 
#' @param h step-lenght
#' @param pi initial probabilities
#' @param T sub-intensity
#' @param beta parametor of transformation
#' @param obs the observations
#' @param weight weight of the observations
#' @param rcens censored observations
#' @param rcweight weight of the censored observations
#' 
logLikelihoodMLogNormal_RK <- function(h, pi, T, beta, obs, weight, rcens, rcweight) {
    .Call(`_matrixdist_logLikelihoodMLogNormal_RK`, h, pi, T, beta, obs, weight, rcens, rcweight)
}

#' Loglikelihood of matrix Log-Logistic using RK
#' 
#' Loglikelihood for a sample 
#' @param h step-lenght
#' @param pi initial probabilities
#' @param T sub-intensity
#' @param beta parametor of transformation
#' @param obs the observations
#' @param weight weight of the observations
#' @param rcens censored observations
#' @param rcweight weight of the censored observations
#' 
logLikelihoodMLogLogistic_RK <- function(h, pi, T, beta, obs, weight, rcens, rcweight) {
    .Call(`_matrixdist_logLikelihoodMLogLogistic_RK`, h, pi, T, beta, obs, weight, rcens, rcweight)
}

#' Loglikelihood of matrix Gompertz using RK
#' 
#' Loglikelihood for a sample 
#' @param h step-lenght
#' @param pi initial probabilities
#' @param T sub-intensity
#' @param beta parametor of transformation
#' @param obs the observations
#' @param weight weight of the observations
#' @param rcens censored observations
#' @param rcweight weight of the censored observations
#' 
logLikelihoodMGompertz_RK <- function(h, pi, T, beta, obs, weight, rcens, rcweight) {
    .Call(`_matrixdist_logLikelihoodMGompertz_RK`, h, pi, T, beta, obs, weight, rcens, rcweight)
}

#' Loglikelihood of matrix GEV using RK
#' 
#' Loglikelihood for a sample 
#' @param h step-lenght
#' @param pi initial probabilities
#' @param T sub-intensity
#' @param beta parametor of transformation
#' @param obs the observations
#' @param weight weight of the observations
#' @param rcens censored observations
#' @param rcweight weight of the censored observations
#' 
logLikelihoodMGEVD_RK <- function(h, pi, T, beta, obs, weight, rcens, rcweight) {
    .Call(`_matrixdist_logLikelihoodMGEVD_RK`, h, pi, T, beta, obs, weight, rcens, rcweight)
}

#' Applies the inverse of the GEV but giving back the vector in reverse order
#' 
#' Used for EM step
#' @param observations the observations
#' @param weights weithgs of the observations
#' @param beta parameters of the GEV
#' 
reversTransformData <- function(observations, weights, beta) {
    .Call(`_matrixdist_reversTransformData`, observations, weights, beta)
}

#' Derivative of matrix Weibull
#' 
#' Can be used to increase performance
#' @param h step-lenght
#' @param pi initial probabilities
#' @param T sub-intensity
#' @param beta parametor of transformation
#' @param obs the observations
#' @param weight weight of the observations
#' @param rcens censored observations
#' @param rcweight weight of the censored observations
#' 
derivativeMatrixWeibull <- function(h, obs, weight, rcens, rcweight, pi, T, beta) {
    .Call(`_matrixdist_derivativeMatrixWeibull`, h, obs, weight, rcens, rcweight, pi, T, beta)
}

#' Embedded Markov chain of a sub-intensity matrix
#' 
#' Returns the transition probabilities of the embedded Markov chain determined the sub-intensity matrix 
#' @param T A sub-intensity matrix
#' @return The embedded Markov chain
#' 
embeddedMC <- function(T) {
    .Call(`_matrixdist_embeddedMC`, T)
}

#' Cumulate matrix
#' 
#' Creates a new matrix with entries the cumulated rows of \code{A}
#' @param A A matrix
#' @return The cumulated matrix
cumulateMatrix <- function(A) {
    .Call(`_matrixdist_cumulateMatrix`, A)
}

#' Cumulate vector
#' 
#' Creates a new vector with entries the cumulated entries of \code{A}
#' @param A A vector
#' @return The cumulated vector
cumulateVector <- function(A) {
    .Call(`_matrixdist_cumulateVector`, A)
}

#' Initial state of Markov jump process
#' 
#' Given the accumulated values of the initial probabilities \code{Pi} and a uniform value \code{u}, it returns the initial state of a Markov jump process
#' @param cumulatedPi A vector
#' @param u A random value in (0,1)
#' @return The initial state of the Markov jump process
initialState <- function(cumulatedPi, u) {
    .Call(`_matrixdist_initialState`, cumulatedPi, u)
}

#' New state in a Markov jump process
#' 
#' Given a transition matrix \code{Q}, a uniform value \code{u}, and a previous state \code{k}, it returns the new state of a Markov jump process
#' @param previousState Previous state of the Markov jump process
#' @param cumulatedEmbeddedMC A transition matrix
#' @param u A random value in (0,1)
#' @return The next state of the Markov jump process
newState <- function(previousState, cumulatedEmbeddedMC, u) {
    .Call(`_matrixdist_newState`, previousState, cumulatedEmbeddedMC, u)
}

#' Random phase-type
#' 
#' Generates a sample of size \code{n} from a phase-type distribution with parameters \code{pi} and \code{T}
#' @param n Sample size
#' @param pi Initial probabilities
#' @param T sub-intensity matrix
#' @return The simulated sample
#' 
rphasetype <- function(n, pi, T) {
    .Call(`_matrixdist_rphasetype`, n, pi, T)
}

#' Random inhomogeneous phase-type
#' 
#' Generates a sample of size \code{n} from an inhomogeneous phase-type distribution with parameters \code{pi}, \code{T} and \code{beta}
#' @param n Sample size
#' @param dist_type Type of IPH: "Pareto", "Weibull", "Gompertz"
#' @param pi Initial probabilities
#' @param T sub-intensity matrix
#' @param beta Parameter of the transformation
#' @return The simulated sample
#' 
riph <- function(n, dist_type, pi, T, beta) {
    .Call(`_matrixdist_riph`, n, dist_type, pi, T, beta)
}

#' Random matrix GEVD
#' 
#' Generates a sample of size \code{n} from an inhomogeneous phase-type distribution with parameters \code{pi}, \code{T} and \code{beta}
#' @param n Sample size
#' @param pi Initial probabilities
#' @param T sub-intensity matrix
#' @param mu Location parameter
#' @param sigma Scale parameter
#' @param xi Shape parameter: Default 0 which corresponds to the Gumbel case
#' @return The simulated sample
#' 
rmatrixGEVD <- function(n, pi, T, mu, sigma, xi = 0) {
    .Call(`_matrixdist_rmatrixGEVD`, n, pi, T, mu, sigma, xi)
}

#' Phase-type density
#' 
#' Computes the density of phase-type distribution with parameters \code{pi} and \code{T} at \code{x}
#' @param x non-negative value
#' @param pi Initial probabilities
#' @param T sub-intensity matrix
#' @return The density at \code{x}
#' 
phdensity <- function(x, pi, T) {
    .Call(`_matrixdist_phdensity`, x, pi, T)
}

#' Phase-type cdf or tail
#' 
#' Computes the cdf of phase-type distribution with parameters \code{pi} and \code{T} at \code{x}
#' @param x non-negative value
#' @param pi Initial probabilities
#' @param T sub-intensity matrix
#' @param lower_tail cdf or tail
#' @return The cdf (tail) at \code{x}
#' 
phcdf <- function(x, pi, T, lower_tail = TRUE) {
    .Call(`_matrixdist_phcdf`, x, pi, T, lower_tail)
}

#' k moment of a phase-type
#' 
#' Computes the k moment of phase-type distribution with parameters \code{pi} and \code{T}
#' @param k Integer value
#' @param pi Initial probabilities
#' @param T sub-intensity matrix
#' @return The k moment
#' 
phmoment <- function(k, pi, T) {
    .Call(`_matrixdist_phmoment`, k, pi, T)
}

#' Laplace transform of a phase-type
#' 
#' Computes the Laplace transform at \code{s} of a phase-type distribution with parameters \code{pi} and \code{T}
#' @param s real value
#' @param pi Initial probabilities
#' @param T sub-intensity matrix
#' @return Laplace transform
#' 
phLaplace <- function(s, pi, T) {
    .Call(`_matrixdist_phLaplace`, s, pi, T)
}

#' Matrix Weibull density
#' 
#' Computes the density of a matrix Weibull distribution with parameters \code{pi}, \code{T} and \code{beta} at \code{x}
#' @param x non-negative value
#' @param pi Initial probabilities
#' @param T sub-intensity matrix
#' @param beta shape parameter
#' @return The density at \code{x}
#' 
mWeibullden <- function(x, pi, T, beta) {
    .Call(`_matrixdist_mWeibullden`, x, pi, T, beta)
}

#' Matrix Weibull cdf
#' 
#' Computes the cdf (tail) of a matrix Weibull distribution with parameters \code{pi}, \code{T} and \code{beta} at \code{x}
#' @param x non-negative value
#' @param pi Initial probabilities
#' @param T sub-intensity matrix
#' @param beta shape parameter
#' @param lower_tail cdf or tail
#' @return The cdf (tail) at \code{x}
#' 
mWeibullcdf <- function(x, pi, T, beta, lower_tail) {
    .Call(`_matrixdist_mWeibullcdf`, x, pi, T, beta, lower_tail)
}

RunFunction <- function(a, func) {
    .Call(`_matrixdist_RunFunction`, a, func)
}

#' Matrix Pareto density
#' 
#' Computes the density of a matrix Pareto distribution with parameters \code{pi}, \code{T} and \code{beta} at \code{x}
#' @param x non-negative value
#' @param pi Initial probabilities
#' @param T sub-intensity matrix
#' @param beta scale parameter
#' @return The density at \code{x}
#' 
mParetoden <- function(x, pi, T, beta) {
    .Call(`_matrixdist_mParetoden`, x, pi, T, beta)
}

#' Matrix Pareto cdf
#' 
#' Computes the cdf (tail) of a matrix Pareto distribution with parameters \code{pi}, \code{T} and \code{beta} at \code{x}
#' @param x non-negative value
#' @param pi Initial probabilities
#' @param T sub-intensity matrix
#' @param beta shape parameter
#' @param lower_tail cdf or tail
#' @return The cdf (tail) at \code{x}
#' 
mParetocdf <- function(x, pi, T, beta, lower_tail = TRUE) {
    .Call(`_matrixdist_mParetocdf`, x, pi, T, beta, lower_tail)
}

#' Matrix LogNormal density
#' 
#' Computes the density of a matrix LogNormal distribution with parameters \code{pi}, \code{T} and \code{beta} at \code{x}
#' @param x non-negative value
#' @param pi Initial probabilities
#' @param T sub-intensity matrix
#' @param beta shape parameter
#' @return The density at \code{x}
#' 
mLogNormalden <- function(x, pi, T, beta) {
    .Call(`_matrixdist_mLogNormalden`, x, pi, T, beta)
}

#' Matrix LogNormal cdf
#' 
#' Computes the cdf (tail) of a matrix LogNormal distribution with parameters \code{pi}, \code{T} and \code{beta} at \code{x}
#' @param x non-negative value
#' @param pi Initial probabilities
#' @param T sub-intensity matrix
#' @param beta shape parameter
#' @param lower_tail cdf or tail
#' @return The cdf (tail) at \code{x}
#' 
mLogNormalcdf <- function(x, pi, T, beta, lower_tail = TRUE) {
    .Call(`_matrixdist_mLogNormalcdf`, x, pi, T, beta, lower_tail)
}

#' Matrix Log-Logistic density
#' 
#' Computes the density of a matrix Log-Logistic distribution with parameters \code{pi}, \code{T} and \code{beta} at \code{x}
#' @param x non-negative value
#' @param pi Initial probabilities
#' @param T sub-intensity matrix
#' @param beta scale parameter
#' @return The density at \code{x}
#' 
mLogLogisticden <- function(x, pi, T, beta) {
    .Call(`_matrixdist_mLogLogisticden`, x, pi, T, beta)
}

#' Matrix Log-Logistic cdf
#' 
#' Computes the cdf (tail) of a matrix Log-Logistic distribution with parameters \code{pi}, \code{T} and \code{beta} at \code{x}
#' @param x non-negative value
#' @param pi Initial probabilities
#' @param T sub-intensity matrix
#' @param beta shape parameter
#' @param lower_tail cdf or tail
#' @return The cdf (tail) at \code{x}
#' 
mLogLogisticcdf <- function(x, pi, T, beta, lower_tail = TRUE) {
    .Call(`_matrixdist_mLogLogisticcdf`, x, pi, T, beta, lower_tail)
}

#' Matrix Gompertz density
#' 
#' Computes the density of a matrix Gompertz distribution with parameters \code{pi}, \code{T} and \code{beta} at \code{x}
#' @param x non-negative value
#' @param pi Initial probabilities
#' @param T sub-intensity matrix
#' @param beta parameter
#' @return The density at \code{x}
#' 
mGompertzden <- function(x, pi, T, beta) {
    .Call(`_matrixdist_mGompertzden`, x, pi, T, beta)
}

#' Matrix Gompertz cdf
#' 
#' Computes the cdf (tail) of a matrix Gompertz distribution with parameters \code{pi}, \code{T} and \code{beta} at \code{x}
#' @param x non-negative value
#' @param pi Initial probabilities
#' @param T sub-intensity matrix
#' @param beta shape parameter
#' @param lower_tail cdf or tail
#' @return The cdf (tail) at \code{x}
#' 
mGompertzcdf <- function(x, pi, T, beta, lower_tail = TRUE) {
    .Call(`_matrixdist_mGompertzcdf`, x, pi, T, beta, lower_tail)
}

#' Matrix GEV density
#' 
#' Computes the density of a matrix GEV distribution with parameters \code{pi}, \code{T} and \code{beta} at \code{x}
#' Dont allow for atoms in zero
#' @param x non-negative value
#' @param pi Initial probabilities
#' @param T sub-intensity matrix
#' @param mu  location parameter
#' @param sigma scale parameter
#' @param xi shape parameter
#' @return The density at \code{x}
#' 
mGEVDden <- function(x, pi, T, mu, sigma, xi) {
    .Call(`_matrixdist_mGEVDden`, x, pi, T, mu, sigma, xi)
}

#' Matrix GEV cdf
#' 
#' Computes the cdf (tail) of a matrix GEV distribution with parameters \code{pi}, \code{T} and \code{beta} at \code{x}
#' @param x non-negative value
#' @param pi Initial probabilities
#' @param T sub-intensity matrix
#' @param mu  location parameter
#' @param sigma scale parameter
#' @param xi shape parameter
#' @param lower_tail cdf or tail
#' @return The cdf (tail) at \code{x}
#' 
mGEVDcdf <- function(x, pi, T, mu, sigma, xi, lower_tail = TRUE) {
    .Call(`_matrixdist_mGEVDcdf`, x, pi, T, mu, sigma, xi, lower_tail)
}

#' Product of two matrices
#' @param a matrix
#' @param b matrix
#' @return Computes C = A * B
#' 
matrix_product <- function(a, b) {
    .Call(`_matrixdist_matrix_product`, a, b)
}

#' Add matrices
#' 
#' Computes C =  A + B 
#' @param A A matrix
#' @param B A matrix
#' 
matrix_sum <- function(A, B) {
    .Call(`_matrixdist_matrix_sum`, A, B)
}

#' L-oo norm of a matrix
#' 
#' Computes the L-oo norm of a matrix \code{A}, which is defined as:
#' L-oo A =  max ( 1 <= I <= M ) sum ( 1 <= J <= N ) abs ( A(I,J) ).
#' @param A A matrix
LInf_norm <- function(A) {
    .Call(`_matrixdist_LInf_norm`, A)
}

#' Solves a system with multiple right hand sides
#' 
#' AX=B which can be decompose as LUX=B and finds X
#' When B is the identity matrix the solution is the inverse of A
#' @param A1 a matrix
#' @param B a matrix
#' 
solve_linear_system <- function(A1, B) {
    .Call(`_matrixdist_solve_linear_system`, A1, B)
}

#' Inverse of a matrix
#' 
#' Computes the inverse
#' @param A a matrix
#' 
matrix_inverse <- function(A) {
    .Call(`_matrixdist_matrix_inverse`, A)
}

#' Matrix exponential algorithm
#' 
#' MATLAB's built-in algorithm - Pade approximation
#' @param A a matrix
#' 
matrix_exponential <- function(A) {
    .Call(`_matrixdist_matrix_exponential`, A)
}

#' Maximum entry in a matrix
#' 
#' Find the maximum entry
#' @param A a matrix
#' 
matrixMax <- function(A) {
    .Call(`_matrixdist_matrixMax`, A)
}

#' Maximum entry in the diagonal of a matrix
#' 
#' @param A a matrix
matrixMaxDiagonal <- function(A) {
    .Call(`_matrixdist_matrixMaxDiagonal`, A)
}

#' Computes A^n
#' 
#' @param n integer
#' @param A a matrix
#' 
matrix_power <- function(n, A) {
    .Call(`_matrixdist_matrix_power`, n, A)
}

#' Clone a vector 
#' 
#' @param v a vector
#' 
clone_vector <- function(v) {
    .Call(`_matrixdist_clone_vector`, v)
}

#' Clone a matrix 
#' 
#' @param m a matrix
#' 
clone_matrix <- function(m) {
    .Call(`_matrixdist_clone_matrix`, m)
}

#' Creates the matrix  (A1, B1 ; 0, A2)
#' 
#' @param A1 a matrix
#' @param A2 a matrix
#' @param B1 a matrix
#' 
matrix_VanLoan <- function(A1, A2, B1) {
    .Call(`_matrixdist_matrix_VanLoan`, A1, A2, B1)
}

#' Creates a matrix with the given vector in the diagonal
#' 
#' @param vec a vector
#' 
diagonal_vector <- function(vec) {
    .Call(`_matrixdist_diagonal_vector`, vec)
}

#' Computes the initial distriubtion and sub-intensity of the sum of PH
#' 
#' @param pi1 initial distribution
#' @param T1 sub-intensity
#' @param pi2 initial distribution
#' @param T2 sub-intensity
#' 
sumPH <- function(pi1, T1, pi2, T2) {
    .Call(`_matrixdist_sumPH`, pi1, T1, pi2, T2)
}

#' Random structure of a phase-type
#' 
#' Generates random parameters \code{pi} and \code{T} of a phase-type distribution of dimension \code{p} with chosen structure
#' @param p Dimension of the phase-type
#' @param structure Type of structure: "General", "Hyperexponential", "GErlang", "Coxian" or "GCoxian"
#' @param scale_factor A factor that multiplies the sub-intensity matrix
#' @return Random parameters \code{pi} and \code{T} of a phase-type
#' 
random_structure <- function(p, structure = "General", scale_factor = 1) {
    .Call(`_matrixdist_random_structure`, p, structure, scale_factor)
}

